# Generated by Django 3.1.4 on 2020-12-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201227_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='username',
            new_name='userID',
        ),
    ]
